name       : et
version    : 4.0.4
release    : 2
source     :
    - https://github.com/MisterTea/EternalTCP/archive/et-v4.0.4.tar.gz : 74c5d81821ae8350c1d65c0f5393dfb2fe2b1014db601de1d05c3599afcf5830
license    : Apache-2.0
component  : network.remote
summary    : Re-Connectable TCP connection
description: |
    Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session.
builddeps  :
    - pkgconfig(gflags)
    - pkgconfig(libglog)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
    - libboost-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
