name       : et
version    : 5.1.10
release    : 7
source     :
    - https://github.com/MisterTea/EternalTerminal/archive/et-v5.1.10.tar.gz : cfe368b3b79d5d07d59ee0437d6a7b838e6162ae85ffc71ca7988b37b46a477b
license    : Apache-2.0
component  : network.remote
summary    : Re-Connectable TCP connection
description: |
    Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session.
builddeps  :
    - pkgconfig(gflags)
    - pkgconfig(libsodium)
    - pkgconfig(ncursesw)
    - pkgconfig(protobuf)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-to-latest-FindSodium.cmake-file-from-upstream.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
