name       : et
version    : 5.1.8
release    : 6
source     :
    - https://github.com/MisterTea/EternalTerminal/archive/et-v5.1.8.tar.gz : da30ae120fd5bda3939909c27a91a857f23cfe0648b7e3905dfb0b89f91a82e8
license    : Apache-2.0
component  : network.remote
summary    : Re-Connectable TCP connection
description: |
    Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session.
builddeps  :
    - pkgconfig(gflags)
    - pkgconfig(libsodium)
    - pkgconfig(ncursesw)
    - pkgconfig(protobuf)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-to-latest-FindSodium.cmake-file-from-upstream.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install