name       : et
version    : 4.1.2
release    : 3
source     :
    - https://github.com/MisterTea/EternalTCP/archive/et-v4.1.2.tar.gz : 94aeab8fbebe2df843aa324659d418ba9061b9bbfef8b31d805e95987f28122e
license    : Apache-2.0
component  : network.remote
summary    : Re-Connectable TCP connection
description: |
    Eternal Terminal (ET) is a remote shell that automatically reconnects without interrupting the session.
builddeps  :
    - pkgconfig(gflags)
    - pkgconfig(libglog)
    - pkgconfig(libsodium)
    - pkgconfig(protobuf)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-to-latest-FindSodium.cmake-file-from-upstream.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
